### ISSUE TITLE
strings with accents are printed with quotes 

### ISSUE THREAD

**Issue by arademaker** [fare/fare-csv#3]
How can I avoid it? In my case all fields are single words and I would like to avoid quotes.

**Comment by fare** [comment]
Right now, you have to modify the definition of char-needs-quoting so it be more lax.

If you have a better suggestion on how to improve this function so it keeps working in as many contexts as possible, I'm all ears.

**Comment by arademaker** [comment]
I don't have a clear list of cases were single words with accents without quotes would cause a problem. I believe we can close this issue for now.
