### ISSUE TITLE
Which BSD license?

### ISSUE THREAD

**Issue by jgarte** [fare/fare-csv#4]
@fare 

Hi, I'm trying to package this library for GNU Guix but I'm not sure which BSD version it is release under?

**Comment by fare** [comment]
BSD no advertising restrictions (2 clauses? Not sure the nomenclature) I can re-license under MIT (Expat) and/or Apache 2, too, if that helps.

**Comment by jgarte** [comment]
> I can re-license under MIT (Expat) and/or Apache 2, too, if that helps.

@fare Hi, however you like. Just let me know which license you'd like to use and I'll update the Guix patch so we can merge the latest package with the chosen license:

https://issues.guix.gnu.org/59844

all best

**Comment by fare** [comment]
I pushed a 1.0.4 that uses MIT.
(NB: I also made small updates to fare-utils, fare-stumpwm)

**Comment by jgarte** [comment]
> I pushed a 1.0.4 that uses MIT. (NB: I also made small updates to fare-utils, fare-stumpwm)

@fare Where did you push it to? I still see `1.0.1` here: https://github.com/fare/fare-csv/blob/39fcada5db2899af172454899ff13a07c62ebdb9/fare-csv.asd#L6

**Comment by fare** [comment]
Aha, my origin was still https://gitlab.common-lisp.net/frideau/fare-csv but I now pushed on github, too.

**Comment by jgarte** [comment]
@fare Which source git repo do you prefer that I use? GitLab?

**Comment by fare** [comment]
It's the gitlab from common-lisp.net, and yes, for now it's still the official repository.

**Comment by jgarte** [comment]
On Wed, 07 Dec 2022 09:04:34 -0800 François-René Rideau ***@***.***> wrote:
> It's the gitlab from common-lisp.net, and yes, for now it's still the official repository.

Cool, thanks for the reply

**Comment by fare** [comment]
(Also note that the code is stable and not under active development anymore--last code change in 2017, and not that many since 2009; patches welcome, but then again, I'd probably surrender ownership to anyone with big patches.)

**Comment by jgarte** [comment]
On Wed, 07 Dec 2022 12:00:08 -0800 François-René Rideau ***@***.***> wrote:
> (Also note that the code is stable and not under active development anymore--last code change in 2017, and not that many since 2009; patches welcome, but then again, I'd probably surrender ownership to anyone with big patches.)

Cool, Thanks for the insight on the state of the project.

all best
